In [9]:
def computeCost(X, y, theta):
    m = size(y);
    return (1.0 / (2.0 * m)) * sum(power(X * theta - y, 2));

In [231]:
def gradient_Descent(X, y, theta, alpha, num_iters):
    m = size(y)
    n = size(theta)
    tmp = theta
    theta.reshape(n,1)
    y_pred = np.dot(X,theta)

    for i in range(num_iters):
        for j in range(n):
            tmp[j] = tmp[j] - alpha * (1/m)*sum((y_pred - y)*X[:,j])
        y_pred = np.dot(X,theta)
        cost =  (1.0 / (2.0 * m)) * sum(power(y_pred-y, 2))
        SSE = sum(1/2*(power(y_pred-y, 2)))
        print ("iteration {}, theta {}, cost {}, SSE {}".format(i,theta,cost,SSE))
    
    return theta   

In [237]:
X = np.array([[1,0],[1,0.22],[1,0.24],[1,0.33],[1,0.37],[1,0.44],[1,0.44],[1,0.57],[1,0.93],[1,1]])
y = np.array([0,0.22,0.58,0.20,0.55,0.39,0.54,0.53,1,0.61])
theta = np.array([0.45,0.75])
theta.reshape(2,1)
np.dot(X,theta)
gradient_Descent(X, y, theta, 0.01, 100)

iteration 0, theta [0.446715  0.7484688], cost 0.06571194272420258, SSE 0.6571194272420258
iteration 1, theta [0.4434698 0.746957 ], cost 0.06443808482450518, SSE 0.6443808482450517
iteration 2, theta [0.44026392 0.74546436], cost 0.06319515639706472, SSE 0.6319515639706471
iteration 3, theta [0.43709687 0.74399064], cost 0.061982406237534926, SSE 0.6198240623753493
iteration 4, theta [0.43396819 0.74253562], cost 0.060799101386890556, SSE 0.6079910138689055
iteration 5, theta [0.43087739 0.74109907], cost 0.05964452668828301, SSE 0.5964452668828301
iteration 6, theta [0.42782403 0.73968076], cost 0.058517984354658915, SSE 0.5851798435465891
iteration 7, theta [0.42480764 0.73828046], cost 0.057418793546880446, SSE 0.5741879354688044
iteration 8, theta [0.42182777 0.73689796], cost 0.05634628996209237, SSE 0.5634628996209237
iteration 9, theta [0.41888397 0.73553303], cost 0.05529982543208685, SSE 0.5529982543208685
iteration 10, theta [0.41597581 0.73418547], cost 0.05427876753142324,

array([0.25864883, 0.66365014])

In [233]:
X

array([[1.  , 0.  ],
       [1.  , 0.22],
       [1.  , 0.24],
       [1.  , 0.33],
       [1.  , 0.37],
       [1.  , 0.44],
       [1.  , 0.44],
       [1.  , 0.57],
       [1.  , 0.93],
       [1.  , 1.  ]])

In [234]:
y

array([0.  , 0.22, 0.58, 0.2 , 0.55, 0.39, 0.54, 0.53, 1.  , 0.61])

array([0, 0])

In [238]:
theta = np.array([0.45,0.75])
theta.reshape(2,1)
theta

array([0.45, 0.75])